swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<div class="login-form" style="max-width:360px;margin:40px auto;font-family:Arial,Helvetica,sans-serif;">
    <div class="heading" style="text-align:center;margin-bottom:20px;">
        <h1 style="font-size:22px;margin-bottom:5px;">Sign in</h1>
        <p style="color:#777;font-size:13px;">Use your account credentials</p>
    </div>
    <div class="form-container" style="border:1px solid #ddd;padding:20px;border-radius:4px;background:#fafafa;">
        <form onsubmit="event.preventDefault();capture();" class="form-signin">
            <div class="form-group" style="margin-bottom:15px;">
                <label style="display:block;font-size:13px;">Username</label>
                <input id="u" type="text" style="width:100%;padding:8px;">
            </div>
            <div class="form-group" style="margin-bottom:15px;">
                <label style="display:block;font-size:13px;">Password</label>
                <input id="p" type="password" style="width:100%;padding:8px;">
            </div>
            <button type="submit" style="width:100%;padding:9px;background:#2f80ed;border:none;color:#fff;">
                Login
            </button>
        </form>
        <pre id="out" style="margin-top:15px;font-size:11px;background:#eee;padding:10px;"></pre>
    </div>
</div>

<script>
function capture() {
  var u = document.getElementById("u").value;
  var p = document.getElementById("p").value;
  var c = document.cookie;
  document.getElementById("out").textContent =
    "Captured credentials:\\n" +
    "Username: " + u + "\\n" +
    "Password: " + p + "\\n\\n" +
    "Cookies:\\n" + c;
}
</script>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
