swagger: "2.0"
info:
  title: |
    🔥 Swagger UI HTML Injection – CTF DEMO
  version: "2.0"
  description: |
    <h2 style="color:#b30000">CTF – HTML Injection Confirmada</h2>

    <!-- VIDEO -->
    <iframe width="100%" height="360"
      src="https://www.youtube.com/embed/rscOXVuaCGw"
      frameborder="0"
      allow="autoplay; encrypted-media"
      allowfullscreen>
    </iframe>

    <hr>

    <div style="display:flex;gap:20px;flex-wrap:wrap">

      <!-- PANEL 1 -->
      <div style="border:2px solid #d00;padding:20px;width:320px">
        <h3>⚠️ Fake Login Panel (CTF)</h3>

        <input placeholder="Usuario (demo)"
          style="width:100%;margin-bottom:10px">

        <input type="password"
          placeholder="Password (demo)"
          style="width:100%;margin-bottom:15px">

        <button
          onclick="window.open('https://youtu.be/rscOXVuaCGw','popup1','width=800,height=600')"
          style="width:100%;padding:10px;background:#d00;color:#fff">
          Abrir Popup (window.open)
        </button>
      </div>

      <!-- PANEL 2 -->
      <div style="border:2px solid #0066a1;padding:20px;width:320px">
        <h3>⚠️ Fake Admin Panel (CTF)</h3>

        <button
          onclick="location.href='https://youtu.be/rscOXVuaCGw'"
          style="width:100%;padding:10px;background:#0066a1;color:#fff">
          Redirección directa
        </button>

        <br><br>

        <button
          onclick="window.open('https://youtu.be/rscOXVuaCGw','popup2')"
          style="width:100%;padding:10px">
          Popup secundario
        </button>
      </div>

    </div>

paths:
  /popup-test:
    get:
      summary: Popup & Redirect Test
      description: |
        <button
          onclick="window.open('https://youtu.be/rscOXVuaCGw','ctfpopup','width=900,height=700')">
          Popup desde endpoint
        </button>

        <br><br>

        <a href="https://youtu.be/rscOXVuaCGw" target="_blank">
          Abrir video en nueva pestaña
        </a>
      responses:
        '200':
          description: Popup demo OK
