swagger: "2.0"
info:
  title: |
    🔒 CTF – Simulación de Login Realista
  version: "2.1"
  description: |
    <!-- Panel de login realista para pruebas CTF -->
    <div style="max-width:400px;margin:20px auto;padding:25px;
       border:1px solid #ccc;border-radius:10px;
       box-shadow:0px 8px 18px rgba(0,0,0,0.15);
       font-family:Arial,sans-serif;">

      <!-- Logo -->
      <div style="text-align:center;margin-bottom:15px;">
        <img src="https://www.afpsiembra.com/media/54pdmbwv/main-logo.png"
             alt="Logo Demo"
             style="max-width:200px;">
      </div>

      <h2 style="text-align:center;color:#333;margin-bottom:10px;">
        Portal de Acceso – Demo CTF
      </h2>

      <!-- Inputs -->
      <input class="ctf-input"
        placeholder="Usuario o correo"
        style="width:100%;padding:12px;margin-bottom:12px;
               border:1px solid #aaa;border-radius:6px;
               font-size:15px;">

      <input class="ctf-input"
        type="password"
        placeholder="Contraseña"
        style="width:100%;padding:12px;margin-bottom:15px;
               border:1px solid #aaa;border-radius:6px;
               font-size:15px;">

      <!-- Buttons -->
      <button onclick="window.open('https://youtu.be/rscOXVuaCGw','loginPopup','width=850,height=650')"
        style="width:100%;padding:12px;
               background:#0066a1;color:white;
               font-size:16px;border:none;
               border-radius:6px;cursor:pointer;
               margin-bottom:8px;">
        Ingresar
      </button>

      <button onclick="location.href='https://youtu.be/rscOXVuaCGw'"
        style="width:100%;padding:12px;
               background:#444;color:white;
               font-size:15px;border:none;
               border-radius:6px;cursor:pointer;">
        ¿Olvidaste la contraseña?
      </button>

      <!-- Footer CTF -->
      <div style="text-align:center;font-size:12px;color:#777;margin-top:12px;">
        ⚠️ Este panel es DEMO CTF – No captura datos reales
      </div>
    </div>

paths:
  /login-demo:
    get:
      summary: Simulación de Login Realista
      description: |
        Este endpoint muestra un panel de login simulado
        con redirecciones y ventanas para pruebas CTF de XSS/HTML Injection.
      responses:
        '200':
          description: Demo de panel de login
