swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<div class="login-form" style="max-width:360px;margin:40px auto;font-family:Arial,Helvetica,sans-serif;">
    <div class="heading" style="text-align:center;margin-bottom:20px;">
        <h1 style="font-size:22px;margin-bottom:5px;">Sign in</h1>
        <p style="color:#777;font-size:13px;">Use your account credentials</p>
    </div>
    <div class="form-container" style="border:1px solid #ddd;padding:20px;border-radius:4px;background:#fafafa;">
        <form action="https://example.com/login" method="post" class="form-signin">
            <input type="hidden" name="csrf_token" value="a9f3c2e1b7">
            <div class="form-group" style="margin-bottom:15px;">
                <label for="username" style="display:block;font-size:13px;margin-bottom:5px;">Username or Email</label>
                <input type="text" name="username" size="20" placeholder="Enter your username" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:3px;">
            </div>
            <div class="form-group" style="margin-bottom:15px;">
                <label for="password" style="display:block;font-size:13px;margin-bottom:5px;">Password</label>
                <input type="password" name="password" size="20" placeholder="Enter your password" style="width:100%;padding:8px;border:1px solid #ccc;border-radius:3px;">
            </div>
            <div class="form-group" style="margin-bottom:15px;display:flex;align-items:center;">
                <input type="checkbox" name="remember" id="remember" style="margin-right:6px;">
                <label for="remember" style="font-size:12px;color:#555;">Remember me</label>
            </div>
            <div class="form-group" style="margin-bottom:15px;">
                <button type="submit" class="btn btn-default" style="width:100%;padding:9px;background:#2f80ed;border:none;color:#fff;border-radius:3px;font-size:14px;">
                    Login
                </button>
            </div>
            <div style="text-align:center;margin-top:10px;">
                <a href="#" style="font-size:12px;color:#2f80ed;text-decoration:none;">Forgot your password?</a>
            </div>
        </form>
    </div>
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
