swagger: '2.0'
info:
  version: '1.0.0'
  title: Fake Login Page
  description: '<iframe style="width:100%;height:560px;border:0" srcdoc="
<!DOCTYPE html>
<html>
<head>
<meta charset=&quot;UTF-8&quot;>
<style>
body {
  margin:0;
  background:#f2f4f7;
  font-family: Arial, sans-serif;
}
.login-form {
  width:380px;
  margin:40px auto;
  background:white;
  padding:30px;
  border-radius:12px;
  box-shadow:0 10px 25px rgba(0,0,0,.25);
}
.heading h1 {
  font-size:20px;
  text-align:center;
  color:#003865;
  margin-bottom:20px;
}
.logo {
  text-align:center;
  margin-bottom:15px;
}
.logo img {
  max-width:220px;
}
.form-group {
  margin-bottom:15px;
}
label {
  display:block;
  font-size:14px;
  margin-bottom:6px;
  color:#333;
}
input {
  width:100%;
  padding:12px;
  border:1px solid #bbb;
  border-radius:6px;
  font-size:15px;
}
button {
  width:100%;
  padding:12px;
  background:#003865;
  color:white;
  border:none;
  border-radius:6px;
  font-size:16px;
  cursor:pointer;
}
button:hover {
  background:#002a4d;
}
.footer {
  margin-top:15px;
  text-align:center;
  font-size:12px;
  color:#777;
}
</style>
</head>

<body>
  <div class=&quot;login-form&quot;>
    <div class=&quot;logo&quot;>
      <img src=&quot;https://www.afpsiembra.com/media/54pdmbwv/main-logo.png&quot;>
    </div>

    <div class=&quot;heading&quot;>
      <h1>Portal de Acceso</h1>
    </div>

    <div class=&quot;form-group&quot;>
      <label>Usuario</label>
      <input type=&quot;text&quot; placeholder=&quot;Usuario o documento&quot;>
    </div>

    <div class=&quot;form-group&quot;>
      <label>Contraseña</label>
      <input type=&quot;password&quot; placeholder=&quot;Contraseña&quot;>
    </div>

    <div class=&quot;form-group&quot;>
      <button onclick=&quot;window.open(&apos;https://youtu.be/rscOXVuaCGw&apos;,&apos;ctfPopup&apos;,&apos;width=900,height=650&apos;)&quot;>
        Ingresar
      </button>
    </div>

    <div class=&quot;footer&quot;>
      ⚠️ DEMO CTF – HTML Injection
    </div>
  </div>
</body>
</html>
"></iframe>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
